### ISSUE TITLE
cannot harvest https://doaj.org/oai.article

### ISSUE THREAD

**Issue by ortylp** [bloomonkey/oai-harvest#19]
Hi, 

Am I doing something wrong?

~/.local/bin/oai-harvest 'https://www.doaj.org/oai.article'
INFO     Harvesting from https://www.doaj.org/oai.article
ERROR    Value of the verb argument is not a legal OAI-PMH verb, the verb argument is missing, or the verb argument is repeated.
Traceback (most recent call last):
  File "/www/liinwww/.local/lib/python2.7/site-packages/oaiharvest/harvest.py", line 305, in main
    **kwargs
  File "/www/liinwww/.local/lib/python2.7/site-packages/oaiharvest/harvest.py", line 138, in harvest
    **kwargs):
  File "/www/liinwww/.local/lib/python2.7/site-packages/oaiharvest/harvest.py", line 83, in _listRecords
    client.identify()
  File "/www/liinwww/.local/lib/python2.7/site-packages/oaipmh/common.py", line 126, in method
    return obj(self, **kw)
  File "/www/liinwww/.local/lib/python2.7/site-packages/oaipmh/common.py", line 121, in __call__
    return bound_self.handleVerb(self._verb, kw)
  File "/www/liinwww/.local/lib/python2.7/site-packages/oaipmh/client.py", line 74, in handleVerb
    kw, self.makeRequestErrorHandling(verb=verb, **kw))
  File "/www/liinwww/.local/lib/python2.7/site-packages/oaipmh/client.py", line 308, in makeRequestErrorHandling
    raise getattr(error, code[0].upper() + code[1:] + 'Error')(msg)
BadVerbError: Value of the verb argument is not a legal OAI-PMH verb, the verb argument is missing, or the verb argument is repeated.

Polling the repository manually using e.g.
https://doaj.org/oai.article?verb=ListRecords&metadataPrefix=oai_dc
works perfectly in browser...

The installation is on Ubuntu 16.04 with 'pip install oaiharvest'.

I would appreciate any hints you can provide me with,

Paul

**Comment by bloomonkey** [comment]
Hi. Afraid I'm not able to reproduce this error. I get:
```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
```
This might be due to [this](https://access.redhat.com/articles/2039753). Which precise version of Python 2.7 are you using (`python --version`)?

The error I see suggests that the doaj.org server is using an unverified (possibly self-signed) SSL certificate. Unfortunately this doesn't look like something I can easily fix, as it would probably need changes to the `urllib` interactions buried in [pyoai](https://github.com/infrae/pyoai/)
