### ISSUE TITLE
Attribute error while harvesting

### ISSUE THREAD

**Issue by epatters** [bloomonkey/oai-harvest#35]
When running the command

```
oai-harvest -p arXiv http://export.arxiv.org/oai2
```

I get the error

```
INFO     Harvesting from http://export.arxiv.org/oai2
ERROR    'Record' object has no attribute 'identifier'
Traceback (most recent call last):
  File "/home/epatters/miniconda3/lib/python3.7/site-packages/oaiharvest/harvest.py", line 181, in main
    **kwargs
  File "/home/epatters/miniconda3/lib/python3.7/site-packages/oaiharvest/harvesters/directory_harvester.py", line 65, in harvest
    record.identifier, metadataPrefix
AttributeError: 'Record' object has no attribute 'identifier'
```

after downloading about ~100K records. I've tried several times, each with the same result. I am running Python 3.7 on a Linux system.

**Comment by epatters** [comment]
Update: The error comes from a logging statement about record delete requests. Commenting out the logging statement seems to work around the error.

One final update, in case it helps anybody: to avoid timeouts while harvesting, I also had to increase the [WAIT_MAX](https://github.com/infrae/pyoai/blob/5f6eba1201270d930ed684e15e9b9fc885649d17/src/oaipmh/client.py#L25) constant in [pyoai](https://github.com/infrae/pyoai). With these changes, I successfully harvested the complete arXiv metadata.
